#!/usr/bin/env python3
"""Generate and score a small single-search teacher-trajectory pilot.

The pilot deliberately keeps the stored representation flat rather than using
multi-turn chat messages.  Each candidate has two model-generated stages:

    <think>...</think><search>QUERY</search>
    <information>RETRIEVED DOCS</information>
    <think>...</think><answer>ANSWER</answer>

The first stage is generated by the teacher, the query is sent to the real
retriever, and the second stage is then generated from the question, query,
and retrieved information.  ``format_correct`` and ``answer_correct`` are
intentionally independent; ``eligible`` is their intersection.

The strict validator here is intentionally narrower than the project's
multi-turn reward parser.  It requires exactly one search stage and exactly
one answer stage, in the order shown above, with no extra recognized tags or
text outside the two generated stages.  The information body is treated as
opaque retrieved text, except that it may not contain control tags that would
make the flat representation ambiguous.
"""

from __future__ import annotations

import argparse
import json
import os
import random
import re
import sys
import time
from collections import Counter
from pathlib import Path
from typing import Any, Iterable, Mapping, Sequence


CONTROL_TAGS = ("think", "search", "information", "answer")
TAG_PATTERN = re.compile(r"</?(?:think|search|information|answer)>")
FIRST_STAGE_PATTERN = re.compile(
    r"^\s*<think>(?P<think>.*?)</think>\s*"
    r"<search>(?P<query>.*?)</search>\s*$",
    re.DOTALL,
)
FINAL_STAGE_PATTERN = re.compile(
    r"^\s*<think>(?P<think>.*?)</think>\s*"
    r"<answer>(?P<answer>.*?)</answer>\s*$",
    re.DOTALL,
)
SEARCH_EXTRACTION_PATTERN = re.compile(r"<search>(.*?)</search>", re.DOTALL)
ANSWER_EXTRACTION_PATTERN = re.compile(r"<answer>(.*?)</answer>", re.DOTALL)

SYSTEM_PROMPT = "You are a helpful assistant."
QUERY_INSTRUCTION = (
    "Answer the given question using one real search. Before searching, reason "
    "inside <think> and </think>, then put exactly one search query inside "
    "<search> and </search>. Do not provide an answer in this stage. Output "
    "only the following form, with no extra text: "
    "<think>brief reasoning</think><search>search query</search>\n\n"
    "Question: {question}"
)
ANSWER_INSTRUCTION = (
    "You have exactly one search result for the question below. Read it and "
    "then provide the final answer. Do not search again. Output only the "
    "following form, with no extra text: "
    "<think>brief reasoning</think><answer>short final answer</answer>\n\n"
    "Question: {question}\n\n"
    "Generated search query:\n<search>{query}</search>\n\n"
    "Actual search result:\n<information>{information}</information>"
)


def _json_safe(value: Any) -> Any:
    """Convert common parquet/numpy values into JSON-serializable values."""

    if value is None or isinstance(value, (str, int, float, bool)):
        return value
    if isinstance(value, Mapping):
        return {str(key): _json_safe(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [_json_safe(item) for item in value]
    if hasattr(value, "tolist"):
        return _json_safe(value.tolist())
    return str(value)


def _answers_list(value: Any) -> list[str]:
    value = _json_safe(value)
    if isinstance(value, list):
        return [str(item).strip() for item in value if str(item).strip()]
    if value is None:
        return []
    text = str(value).strip()
    return [text] if text else []


def _normalize_answer(text: str) -> str:
    """Match verl.utils.reward_score.qa_em.normalize_answer semantics."""

    import string

    text = str(text).lower()
    text = "".join(char for char in text if char not in set(string.punctuation))
    text = re.sub(r"\b(a|an|the)\b", " ", text)
    return " ".join(text.split())


def _answer_em(answer: str | None, golden_answers: Sequence[str]) -> bool:
    if answer is None:
        return False
    normalized = _normalize_answer(answer)
    return any(normalized == _normalize_answer(gold) for gold in golden_answers)


def extract_query(text: str) -> str | None:
    """Extract a query for retrieval even when the stage is malformed.

    The first well-delimited search body is used.  Format correctness is
    checked separately, so a malformed candidate can still receive real
    retrieved information and be retained for analysis.
    """

    matches = SEARCH_EXTRACTION_PATTERN.findall(text or "")
    if not matches:
        return None
    query = matches[0].strip()
    return query if query else None


def extract_answer(text: str) -> str | None:
    """Extract the last answer body, independently of format validity."""

    matches = ANSWER_EXTRACTION_PATTERN.findall(text or "")
    if not matches:
        return None
    answer = matches[-1].strip()
    return answer if answer else None


def _tag_counts(text: str) -> Counter[str]:
    return Counter(TAG_PATTERN.findall(text or ""))


def validate_flat_trajectory(
    raw_query_output: str,
    information: str,
    raw_answer_output: str,
) -> tuple[bool, list[str], str]:
    """Strictly validate one-search flat trajectory format.

    Empty ``think`` bodies are accepted as syntactically valid, while the
    search query and final answer bodies must be non-empty.  This keeps the
    filter about structure rather than judging reasoning quality.
    """

    reasons: list[str] = []
    query_match = FIRST_STAGE_PATTERN.fullmatch(raw_query_output or "")
    answer_match = FINAL_STAGE_PATTERN.fullmatch(raw_answer_output or "")

    if query_match is None:
        reasons.append("query_stage_not_exactly_think_then_search")
    if answer_match is None:
        reasons.append("answer_stage_not_exactly_think_then_answer")

    query = query_match.group("query").strip() if query_match else ""
    answer = answer_match.group("answer").strip() if answer_match else ""
    if query_match is not None and not query:
        reasons.append("empty_search_query")
    if answer_match is not None and not answer:
        reasons.append("empty_final_answer")

    generated_text = f"{raw_query_output or ''}\n{raw_answer_output or ''}"
    expected_counts = Counter(
        {
            "<think>": 2,
            "</think>": 2,
            "<search>": 1,
            "</search>": 1,
            "<answer>": 1,
            "</answer>": 1,
        }
    )
    generated_counts = _tag_counts(generated_text)
    for tag, expected in expected_counts.items():
        if generated_counts[tag] != expected:
            reasons.append(
                f"tag_count_{tag.replace('<', '').replace('>', '').replace('/', 'close_')}"
            )
    if generated_counts["<information>"] or generated_counts["</information>"]:
        reasons.append("information_tag_in_teacher_output")

    if TAG_PATTERN.search(information or ""):
        reasons.append("control_tag_inside_information")

    valid = not reasons
    trajectory = (
        f"{(raw_query_output or '').strip()}\n\n"
        f"<information>{(information or '').strip()}</information>\n\n"
        f"{(raw_answer_output or '').strip()}"
    )
    return valid, reasons, trajectory


def _passages_to_string(retrieval_result: Any) -> str:
    """Use the same document formatting as Tree-GRPO's retrieval rollout."""

    if retrieval_result is None:
        return ""
    if not isinstance(retrieval_result, list):
        return str(retrieval_result)

    formatted = ""
    if retrieval_result and all(isinstance(item, dict) for item in retrieval_result):
        for index, item in enumerate(retrieval_result):
            document = item.get("document", item)
            if isinstance(document, dict):
                content = document.get("contents", document.get("content", ""))
                if not content:
                    content = json.dumps(document, ensure_ascii=False, sort_keys=True)
            else:
                content = str(document)
            content = str(content)
            lines = content.splitlines()
            title = lines[0] if lines else ""
            body = "\n".join(lines[1:])
            formatted += f"Doc {index + 1}(Title: {title}) {body}\n"
    else:
        for item in retrieval_result:
            formatted += str(item)
    return formatted


def _read_questions(dataset_path: str, num_questions: int, seed: int) -> tuple[list[dict[str, Any]], int]:
    import pandas as pd

    frame = pd.read_parquet(dataset_path)
    required = {"id", "question", "golden_answers"}
    missing = sorted(required.difference(frame.columns))
    if missing:
        raise ValueError(f"Dataset is missing required columns: {missing}")

    rows = frame.to_dict(orient="records")
    order = list(range(len(rows)))
    random.Random(seed).shuffle(order)
    selected: list[dict[str, Any]] = []
    seen_questions: set[str] = set()
    for index in order:
        row = rows[index]
        question = str(row["question"]).strip()
        key = " ".join(question.split())
        if not key or key in seen_questions:
            continue
        seen_questions.add(key)
        selected.append(
            {
                "row_index": index,
                "question_id": str(row["id"]),
                "question": question,
                "gold_answers": _answers_list(row["golden_answers"]),
            }
        )
        if len(selected) == num_questions:
            break

    if len(selected) != num_questions:
        raise ValueError(
            f"Could select only {len(selected)} unique questions from {len(rows)} rows; "
            f"requested {num_questions}"
        )
    return selected, len(rows)


def _build_chat_prompt(tokenizer: Any, user_content: str) -> str:
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": user_content},
    ]
    try:
        return tokenizer.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=True
        )
    except (AttributeError, ValueError, TypeError):
        return f"{SYSTEM_PROMPT}\n\n{user_content}\n\nAssistant:\n"


class TeacherGenerator:
    def __init__(self, args: argparse.Namespace) -> None:
        import torch
        from transformers import AutoModelForCausalLM, AutoTokenizer

        self.torch = torch
        visible = os.environ.get("CUDA_VISIBLE_DEVICES", "")
        if not visible.strip():
            raise RuntimeError(
                "CUDA_VISIBLE_DEVICES must be set explicitly; use CUDA_VISIBLE_DEVICES=4"
            )
        if args.expected_cuda_visible and visible.replace(" ", "") != args.expected_cuda_visible:
            raise RuntimeError(
                "Refusing to run with CUDA_VISIBLE_DEVICES="
                f"{visible!r}; expected {args.expected_cuda_visible!r} for this pilot"
            )
        if not torch.cuda.is_available() or torch.cuda.device_count() != 1:
            raise RuntimeError(
                "Expected exactly one visible CUDA device. "
                f"CUDA_VISIBLE_DEVICES={visible!r}, count={torch.cuda.device_count()}"
            )

        self.device = torch.device("cuda:0")
        torch.manual_seed(args.seed)
        torch.cuda.manual_seed_all(args.seed)
        # PyTorch 2.6 can reject a torch.device here when a physical GPU is
        # remapped through CUDA_VISIBLE_DEVICES, even though cuda:0 allocations
        # work normally. The no-argument form targets the current visible GPU.
        torch.cuda.set_device(0)
        torch.cuda.reset_peak_memory_stats()

        self.tokenizer = AutoTokenizer.from_pretrained(
            args.model_path,
            local_files_only=True,
            trust_remote_code=True,
        )
        self.tokenizer.padding_side = "left"
        if self.tokenizer.pad_token_id is None:
            self.tokenizer.pad_token = self.tokenizer.eos_token

        self.model = AutoModelForCausalLM.from_pretrained(
            args.model_path,
            local_files_only=True,
            trust_remote_code=True,
            torch_dtype=torch.float16,
            low_cpu_mem_usage=True,
        )
        self.model.to(self.device)
        self.model.eval()
        self.model.config.use_cache = True

    def generate(self, user_prompts: Sequence[str], max_new_tokens: int, batch_size: int) -> list[str]:
        prompts = [_build_chat_prompt(self.tokenizer, prompt) for prompt in user_prompts]
        outputs: list[str] = []
        for start in range(0, len(prompts), batch_size):
            batch_prompts = prompts[start : start + batch_size]
            encoded = self.tokenizer(
                batch_prompts,
                return_tensors="pt",
                padding=True,
                truncation=True,
                max_length=2048,
            )
            encoded = {key: value.to(self.device) for key, value in encoded.items()}
            with self.torch.inference_mode():
                generated = self.model.generate(
                    **encoded,
                    do_sample=True,
                    temperature=0.7,
                    top_p=0.9,
                    max_new_tokens=max_new_tokens,
                    pad_token_id=self.tokenizer.pad_token_id,
                    eos_token_id=self.tokenizer.eos_token_id,
                    use_cache=True,
                )
            prompt_width = encoded["input_ids"].shape[1]
            new_tokens = generated[:, prompt_width:]
            outputs.extend(
                self.tokenizer.batch_decode(
                    new_tokens,
                    skip_special_tokens=True,
                    clean_up_tokenization_spaces=False,
                )
            )
            del encoded, generated, new_tokens
            self.torch.cuda.empty_cache()
        return outputs

    def memory_stats(self) -> dict[str, Any]:
        allocated = self.torch.cuda.max_memory_allocated()
        reserved = self.torch.cuda.max_memory_reserved()
        return {
            "device": str(self.device),
            "cuda_visible_devices": os.environ.get("CUDA_VISIBLE_DEVICES"),
            "peak_memory_allocated_bytes": int(allocated),
            "peak_memory_reserved_bytes": int(reserved),
            "peak_memory_allocated_gib": round(allocated / (1024**3), 3),
            "peak_memory_reserved_gib": round(reserved / (1024**3), 3),
        }


def _retrieve(
    retrieval_url: str,
    queries: Sequence[str],
    topk: int,
    timeout: float,
) -> tuple[list[Any | None], str | None]:
    import requests

    if not queries:
        return [], None
    response = requests.post(
        retrieval_url,
        json={"queries": list(queries), "topk": topk, "return_scores": True},
        timeout=timeout,
    )
    response.raise_for_status()
    payload = response.json()
    results = payload.get("result") if isinstance(payload, dict) else None
    if not isinstance(results, list) or len(results) != len(queries):
        raise RuntimeError(
            "Retriever returned an unexpected result shape: "
            f"expected {len(queries)} results, got {type(results).__name__}"
        )
    return results, None


def _write_jsonl(path: Path, records: Iterable[Mapping[str, Any]]) -> None:
    with path.open("w", encoding="utf-8") as handle:
        for record in records:
            handle.write(json.dumps(_json_safe(record), ensure_ascii=False) + "\n")


def run_self_test() -> dict[str, Any]:
    valid_query = "<think>I need to verify the fact.</think><search>capital of France</search>"
    valid_answer = "<think>The retrieved document states the answer.</think><answer>Paris</answer>"
    valid, reasons, trajectory = validate_flat_trajectory(valid_query, "Doc 1(Title: France) Paris", valid_answer)
    assert valid and not reasons
    assert extract_query(valid_query) == "capital of France"
    assert extract_answer(valid_answer) == "Paris"
    assert _answer_em("Paris", ["Paris"])

    wrong_answer = "<think>The document gives a different city.</think><answer>Lyon</answer>"
    valid_wrong, wrong_reasons, _ = validate_flat_trajectory(valid_query, "Doc 1(Title: France) Paris", wrong_answer)
    assert valid_wrong and not wrong_reasons
    assert not _answer_em(extract_answer(wrong_answer), ["Paris"])

    duplicate_search = (
        "<think>First.</think><search>one</search><search>two</search>"
    )
    duplicate_valid, duplicate_reasons, _ = validate_flat_trajectory(
        duplicate_search, "Doc 1(Title: x) y", valid_answer
    )
    assert not duplicate_valid and duplicate_reasons

    missing_answer = "<think>Reason only.</think>"
    assert extract_answer(missing_answer) is None
    return {
        "status": "passed",
        "checks": [
            "valid_single_search_and_answer",
            "independent_wrong_answer_score",
            "duplicate_search_rejected",
            "missing_answer_extraction_false",
        ],
        "example_trajectory": trajectory,
    }


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--model-path",
        default="/home/luwa/Documents/Tree-GRPO/models/Qwen2.5-7B-Instruct",
    )
    parser.add_argument(
        "--dataset-path",
        default="/home/luwa/Documents/Search-R1/data/nq_search/train.parquet",
    )
    parser.add_argument(
        "--output-dir",
        default="/home/luwa/Documents/Tree-GRPO/data/teacher_sft_pilot_qwen2.5_7b",
    )
    parser.add_argument("--num-questions", type=int, default=50)
    parser.add_argument("--samples-per-question", type=int, default=2)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--retrieval-url", default="http://127.0.0.1:8000/retrieve")
    parser.add_argument("--retrieval-topk", type=int, default=3)
    parser.add_argument("--retrieval-timeout", type=float, default=90.0)
    parser.add_argument("--generation-batch-size", type=int, default=2)
    parser.add_argument("--query-max-new-tokens", type=int, default=192)
    parser.add_argument("--answer-max-new-tokens", type=int, default=192)
    parser.add_argument(
        "--expected-cuda-visible",
        default="4",
        help="Safety check for the physical GPU exposed through CUDA_VISIBLE_DEVICES.",
    )
    parser.add_argument("--overwrite", action="store_true")
    parser.add_argument("--dry-run", action="store_true", help="Run CPU-only validator self-tests.")
    parser.add_argument("--self-test", action="store_true", help="Alias for --dry-run validator tests.")
    return parser


def run_pilot(args: argparse.Namespace) -> dict[str, Any]:
    started = time.monotonic()
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    output_paths = [output_dir / name for name in ("candidates.jsonl", "accepted.jsonl", "summary.json")]
    if not args.overwrite:
        existing = [str(path) for path in output_paths if path.exists()]
        if existing:
            raise FileExistsError(
                "Refusing to overwrite existing pilot outputs; pass --overwrite: "
                + ", ".join(existing)
            )

    selected, dataset_rows = _read_questions(args.dataset_path, args.num_questions, args.seed)
    candidate_specs: list[dict[str, Any]] = []
    for question in selected:
        for sample_index in range(args.samples_per_question):
            candidate_specs.append(
                {
                    "candidate_id": f"{question['question_id']}__sample_{sample_index}",
                    "sample_index": sample_index,
                    **question,
                }
            )

    generator = TeacherGenerator(args)
    query_prompts = [QUERY_INSTRUCTION.format(question=item["question"]) for item in candidate_specs]
    query_started = time.monotonic()
    raw_query_outputs = generator.generate(
        query_prompts, args.query_max_new_tokens, args.generation_batch_size
    )
    query_seconds = time.monotonic() - query_started
    if len(raw_query_outputs) != len(candidate_specs):
        raise RuntimeError("Teacher query generation returned the wrong number of outputs")

    queries = [extract_query(output) for output in raw_query_outputs]
    retrieval_results: list[Any | None] = [None] * len(candidate_specs)
    retrieval_errors: list[str | None] = [None] * len(candidate_specs)
    nonempty_indices = [index for index, query in enumerate(queries) if query]
    retrieval_started = time.monotonic()
    if nonempty_indices:
        try:
            batch_results, _ = _retrieve(
                args.retrieval_url,
                [queries[index] for index in nonempty_indices if queries[index] is not None],
                args.retrieval_topk,
                args.retrieval_timeout,
            )
            for index, result in zip(nonempty_indices, batch_results):
                retrieval_results[index] = result
        except Exception as exc:  # Preserve all candidates for failure analysis.
            error = f"{type(exc).__name__}: {exc}"
            for index in nonempty_indices:
                retrieval_errors[index] = error
    for index in range(len(candidate_specs)):
        if not queries[index]:
            retrieval_errors[index] = "missing_search_query"
    retrieval_seconds = time.monotonic() - retrieval_started

    information = [_passages_to_string(result) for result in retrieval_results]
    answer_prompts = [
        ANSWER_INSTRUCTION.format(
            question=item["question"],
            query=queries[index] or "",
            information=information[index],
        )
        for index, item in enumerate(candidate_specs)
    ]
    answer_started = time.monotonic()
    raw_answer_outputs = generator.generate(
        answer_prompts, args.answer_max_new_tokens, args.generation_batch_size
    )
    answer_seconds = time.monotonic() - answer_started
    if len(raw_answer_outputs) != len(candidate_specs):
        raise RuntimeError("Teacher answer generation returned the wrong number of outputs")

    records: list[dict[str, Any]] = []
    for index, item in enumerate(candidate_specs):
        raw_query = raw_query_outputs[index].strip()
        raw_answer = raw_answer_outputs[index].strip()
        format_correct, format_reasons, trajectory = validate_flat_trajectory(
            raw_query, information[index], raw_answer
        )
        extracted_answer = extract_answer(raw_answer)
        answer_correct = _answer_em(extracted_answer, item["gold_answers"])
        failure_reasons = list(format_reasons)
        if extracted_answer is None:
            failure_reasons.append("final_answer_extraction_failed")
        elif not answer_correct:
            failure_reasons.append("final_answer_em_failed")
        if retrieval_errors[index]:
            failure_reasons.append("retrieval_failed")

        records.append(
            {
                "candidate_id": item["candidate_id"],
                "question_id": item["question_id"],
                "row_index": item["row_index"],
                "question": item["question"],
                "sample_index": item["sample_index"],
                "seed": args.seed,
                "gold_answers": item["gold_answers"],
                "raw_query_output": raw_query,
                "extracted_query": queries[index],
                "retrieval_url": args.retrieval_url,
                "retrieval_topk": args.retrieval_topk,
                "retrieval_result": retrieval_results[index],
                "retrieval_error": retrieval_errors[index],
                "information": information[index],
                "raw_answer_output": raw_answer,
                "extracted_answer": extracted_answer,
                "trajectory": trajectory,
                "format_correct": format_correct,
                "answer_correct": answer_correct,
                "eligible": bool(format_correct and answer_correct),
                "format_failure_reasons": format_reasons,
                "failure_reasons": failure_reasons,
            }
        )

    expected_candidates = args.num_questions * args.samples_per_question
    if len(records) != expected_candidates:
        raise RuntimeError(
            f"Expected {expected_candidates} candidates, produced {len(records)}"
        )

    accepted = [record for record in records if record["eligible"]]
    denominator = len(records)
    format_count = sum(bool(record["format_correct"]) for record in records)
    answer_count = sum(bool(record["answer_correct"]) for record in records)
    eligible_count = len(accepted)
    reason_counts: Counter[str] = Counter()
    for record in records:
        reason_counts.update(record["failure_reasons"])

    def metric(numerator: int) -> dict[str, Any]:
        return {
            "numerator": numerator,
            "denominator": denominator,
            "rate": numerator / denominator if denominator else 0.0,
        }

    summary = {
        "status": "completed",
        "config": {
            "model_path": args.model_path,
            "dataset_path": args.dataset_path,
            "output_dir": args.output_dir,
            "num_questions": args.num_questions,
            "samples_per_question": args.samples_per_question,
            "seed": args.seed,
            "temperature": 0.7,
            "top_p": 0.9,
            "retrieval_url": args.retrieval_url,
            "retrieval_topk": args.retrieval_topk,
            "generation_batch_size": args.generation_batch_size,
            "query_max_new_tokens": args.query_max_new_tokens,
            "answer_max_new_tokens": args.answer_max_new_tokens,
            "format_filter": "exactly think/search + information + think/answer, no extra recognized tags",
            "answer_filter": "verl qa_em exact-match normalization against any golden answer",
        },
        "dataset": {
            "rows": dataset_rows,
            "selected_unique_questions": len(selected),
            "selected_question_ids": [item["question_id"] for item in selected],
        },
        "candidates": {
            "expected": expected_candidates,
            "written": len(records),
        },
        "metrics": {
            "format_correct": metric(format_count),
            "answer_correct": metric(answer_count),
            "eligible_intersection": metric(eligible_count),
        },
        "failure_reason_counts": dict(reason_counts.most_common()),
        "timing_seconds": {
            "query_generation": round(query_seconds, 3),
            "retrieval": round(retrieval_seconds, 3),
            "answer_generation": round(answer_seconds, 3),
            "total": round(time.monotonic() - started, 3),
        },
        "gpu": generator.memory_stats(),
        "infrastructure_failures": sorted(
            {record["retrieval_error"] for record in records if record["retrieval_error"]}
        ),
    }

    _write_jsonl(output_paths[0], records)
    _write_jsonl(output_paths[1], accepted)
    with output_paths[2].open("w", encoding="utf-8") as handle:
        json.dump(_json_safe(summary), handle, ensure_ascii=False, indent=2)
        handle.write("\n")
    print(json.dumps(_json_safe(summary), ensure_ascii=False, indent=2))
    return summary


def main(argv: Sequence[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    if args.dry_run or args.self_test:
        print(json.dumps(run_self_test(), ensure_ascii=False, indent=2))
        return 0
    try:
        run_pilot(args)
    except Exception as exc:
        print(f"PILOT FAILED: {type(exc).__name__}: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
